#!/bin/sh

set -e

if [ ! -f "cert.pem" ]; then
    # Use cert.pem from OpenBSD & LibreSSL project
    curl -fO https://raw.githubusercontent.com/libressl-portable/openbsd/master/src/lib/libcrypto/cert.pem
fi

if [ $# -lt 2 ]; then
    echo "$0 <host> <port>"
    exit 1
fi

HOST=$1
PORT=$2

if [ "${PORT}" -lt 0 ] || [ "${PORT}" -gt 65535 ]; then
    echo "Invalid port number"
    exit 1
fi

SCLIENTPARAMS="-connect ${HOST}:${PORT}"
NONVALIDCERT="${HOST}.nonvalidated.cer"
NONVALIDCHAIN="${HOST}.nonvalidated.chain"

echo "Q" \
    | openssl s_client ${SCLIENTPARAMS} \
    | openssl x509 -text >${NONVALIDCERT}

echo "Q" \
    | openssl s_client -showcerts ${SCLIENTPARAMS} >${NONVALIDCHAIN}

openssl verify \
        -CAfile cert.pem \
        -purpose sslserver \
        -untrusted ${NONVALIDCHAIN} \
        ${NONVALIDCERT} \
    | grep "^error " && exit 1


mv ${NONVALIDCERT} ${HOST}.cer
rm -f *.nonvalidated.*
